name: Hello World
author: VP
description: "Greet someone and record the time"
inputs:
  who_to_greet:
    description: "Who to greet"
#    required: true
    default: "World"
outputs:
  time:
    description: The time of the greeting
runs:
  using: "docker"
  # A remote image can be used
  # image: 'docker://node:22-alpine3.19'
  # Also a local one
  image: 'Dockerfile'
  # Override image defined in the local Dockerfile
  # entrypoint: 
  # Override the command of the dockerfile
  args:
    # use an exrepssion for getting the input
    - ${{ inputs.who_to_greet }}
  env:
    HELLO: WORLD
  post-entrypoint: "/cleanup.sh"
  post-if: runner.os == 'linux'
