name: Docker
on: [workflow_dispatch]

jobs:
    docker-job: 
        runs-on: ubuntu-latest
        # By default uses dockerhub so you just need to chose the image and version.
        # For using another registry you must put the complete registry name
        #     for example, ghcr.io/owner/image 
        container: 
            image: node:22-alpine3.19
            # If we use a private image we will need to provide credentials
            # credentials:
            #     username:
            #     password:
            env:
                API_URL: some-url.com
            ports:
                - 80
#            volumes:
#                - vol_name:/patrh/in/container
#                - /path/to/container
#                - /path/in/host:/path/in/container
            options: --cpus 1           # every options in docker create (except network realted ones)

        steps:
            - name: Log Node & OS Versions
              run: |
                node -v
                cat /etc/os-release
            - name: Log Env
              run: echo $API_URL

