name: Docker
on: [workflow_dispatch]

jobs:
    docker-job: 
        runs-on: ubuntu-latest
        # By default uses dockerhub so you just need to chose the image and version.
        # For using another registry you must put the complete registry name
        #     for example, ghcr.io/owner/image 
        container: 
            image: node:22-alpine3.19
            # If we use a private image we will need to provide credentials
            # credentials:
            #     username:
            #     password:
            env:
                API_URL: some-url.com
            ports:
                - 80
#            volumes:
#                - vol_name:/patrh/in/container
#                - /path/to/container
#                - /path/in/host:/path/in/container
#            options: --cpus 1           # every options in docker create (except network realted ones)

        steps:
            - name: Log Node & OS Versions
              run: |
                node -v
                cat /etc/os-release
            - name: Log Env
              run: echo $API_URL
            - name: Create a file
              run: echo 'Some text' > text.txt
            - name: Container in a Step
              uses: docker://node:20-alpine3.20
              with:
                # overrides the entrypoint if necessary
                entrypoint: /usr/local/bin/node
                args: -p 2+3
            - name: Log node version
              uses: docker://node:20-alpine3.20
              with:
                args: -v          
            - name: Show file contents
              uses: docker://node:20-alpine3.20
              with:
                entrypoint: cat
                args: text.txt    
            - uses: actions/checkout@v3
            - name: Run a bash script
              uses: docker://node:20-alpine3.20
              with:
                entrypoint: ./script.sh     # this file must be executable (chmod +x filename)
                args: "Alguna cadena rara que te he puesto porque es un ejemplo pero me he aburrio describir en ingles"


